name: ci/cd
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
      uses: actions/checkout@v4

    - name: setp
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: test coverage
      run: go test -race -coverprofile=coverage.out -covermode=atomic

    - name: upload coverage
      uses: codecov/codecov-action@v3
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: diego-augusto/go-retry